In [1]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
data = load_iris()
print(dir(data)) # 查看data所具有的属性或方法

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']


In [3]:
print(data.DESCR) # 查看数据集的简介

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [44]:
<div class="burk">
# data.data</div><i class="fa fa-lightbulb-o "></i>

In [6]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
###### 导入鸢尾属植物数据集，保持文本不变。

In [8]:
rawdata = pd.DataFrame(data.data,columns=data.feature_names,copy=True)
rawdata['class'] = data.target
rawdata.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [15]:
###### 求出鸢尾属植物萼片长度的平均值、中位数和标准差（第1列，sepallength）

In [9]:
# rawdata['sepal length (cm)'].describe().index

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')

In [84]:
rawdata['sepal length (cm)'].describe()[['mean','50%','std']]

mean    5.843333
50%     5.800000
std     0.828066
Name: sepal length (cm), dtype: float64

In [16]:
###### 创建一种标准化形式的鸢尾属植物萼片长度，其值正好介于0和1之间，这样最小值为0，最大值为1（第1列，sepallength）。

In [9]:
from sklearn.preprocessing import MinMaxScaler

MinMaxFunction = MinMaxScaler()
sepal_length_Scaled = MinMaxFunction.fit_transform(np.array(rawdata['sepal length (cm)']).reshape(-1,1))
# sepal_length_Scaled

In [17]:
###### 找到鸢尾属植物萼片长度的第5和第95百分位数（第1列，sepallength）。

In [86]:
np.percentile(np.array(rawdata['sepal length (cm)']),[5,95])
# np.percentile(rawdata,[5,95],axis = 0)

array([4.6  , 7.255])

In [18]:
###### 把iris_data数据集中的20个随机位置修改为np.nan值。

In [13]:
# np.random.choice(rawdata.values.reshape(1,-1)[0],20)

In [10]:
# random select index & column separately - drawback: can be repetitively
np.random.seed(1)
random_index_list = np.random.randint(0,150,20)
random_column_list = np.random.randint(0,4,20)
pd.DataFrame(list(zip(random_index_list,random_column_list))).head()

0  1
0   37  1
1  140  1
2   72  1
3  137  3
4  133  3

In [261]:
# np.random.seed(1)
# test_list = np.random.choice(range(0,600),20,replace=False)
# test_list

array([446, 404, 509, 455, 201,  23, 415, 548,  66, 165, 334, 329,   0,
       531, 232, 200, 147, 473, 451, 496])

In [12]:
np.random.seed(1)
test_choiced = [[x%150,x//150] for x in np.random.choice(range(0,600),20,replace=False)]
test_choiced

[[146, 2],
 [104, 2],
 [59, 3],
 [5, 3],
 [51, 1],
 [23, 0],
 [115, 2],
 [98, 3],
 [66, 0],
 [15, 1],
 [34, 2],
 [29, 2],
 [0, 0],
 [81, 3],
 [82, 1],
 [50, 1],
 [147, 0],
 [23, 3],
 [1, 3],
 [46, 3]]

In [13]:
rawdata_nan = rawdata.copy()
for i in test_choiced:
    rawdata_nan.iloc[i[0],i[1]] = np.NAN

rawdata_nan.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                NaN               3.5                1.4               0.2   
1                4.9               3.0                1.4               NaN   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [19]:
###### 在iris_data的sepallength中查找缺失值的个数和位置（第1列）。

In [30]:
# np.isnan(rawdata_nan['sepal length (cm)'])

0       True
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23      True
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147     True
148    False
149    False
Name: sepal length (cm), Length: 150, dtype: bool

In [14]:
print('count NaN values',len(np.where(np.isnan(rawdata_nan['sepal length (cm)']))[0]))
print('location NaN values',np.where(np.isnan(rawdata_nan['sepal length (cm)']))[0])

count NaN values 4
location NaN values [  0  23  66 147]


In [20]:
###### 筛选具有 sepallength（第1列）< 5.0 并且 petallength（第3列）> 1.5 的 iris_data行。

In [15]:
rawdata_nan[(rawdata_nan['sepal length (cm)'] < 5) & (rawdata_nan['petal length (cm)'] > 1.5)]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                 4.8               3.4                1.6               0.2   
24                 4.8               3.4                1.9               0.2   
30                 4.8               3.1                1.6               0.2   
57                 4.9               2.4                3.3               1.0   
106                4.9               2.5                4.5               1.7   

     class  
11       0  
24       0  
30       0  
57       1  
106      2

In [21]:
###### 选择没有任何 nan 值的 iris_data行。

In [16]:
# rawdata_nan[np.isnan(rawdata_nan.sum(axis = 1,skipna=False))==False]

In [17]:
rawdata_nan[rawdata_nan.isna().sum(axis = 1) == 0].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   

   class  
2      0  
3      0  
4      0  
6      0  
7      0

In [22]:
###### 计算 iris_data 中sepalLength（第1列）和petalLength（第3列）之间的相关系数。

In [94]:
np.corrcoef(rawdata['sepal length (cm)'].values,rawdata['petal length (cm)'].values)

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

In [18]:
# test_1 = np.array([1.4,1.4,np.nan,1.5,1.4])
# test_2 = np.array([4, 4.9,np.nan,4.6,5])

# np.corrcoef(test_1,test_2,rowvar=False)

In [19]:
# rawdata.info()

In [23]:
###### 找出iris_data是否有任何缺失值。

In [20]:
print('nan value exist' if np.isnan(rawdata_nan).sum().sum() > 0 else 'no nan value')

nan value exist


In [23]:
rawdata_nan

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  NaN               3.5                1.4               0.2   
1                  4.9               3.0                1.4               NaN   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               NaN   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               NaN                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 NaN               3.3                1.7               NaN   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                NaN               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

In [ ]:
###### 在numpy数组中将所有出现的nan替换为0。

In [29]:

column_names

array(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'class'], dtype='<U17')

In [32]:
column_names = np.append(np.array(data.feature_names),'class')
rawdata_zero = pd.DataFrame(np.where(np.isnan(rawdata_nan),0,rawdata_nan),columns=column_names,copy=True)
rawdata_zero.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                0.0               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.0   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [ ]:
###### 找出鸢尾属植物物种中的唯一值和唯一值出现的数量。

In [33]:
rawdata_str = rawdata_zero.astype(str)
rawdata_zero['flag_unique_species'] = rawdata_str['sepal length (cm)']+rawdata_str['sepal width (cm)']+rawdata_str['petal length (cm)']+rawdata_str['petal width (cm)']
rawdata_zero.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                0.0               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.0   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class flag_unique_species  
0    0.0        0.03.51.40.2  
1    0.0        4.93.01.40.0  
2    0.0        4.73.21.30.2  
3    0.0        4.63.11.50.2  
4    0.0        5.03.61.40.2

In [117]:
# rawdata_zero.groupby('flag_unique_species')['flag_unique_species'].count()

flag_unique_species
0.03.04.51.5    1
0.03.05.22.0    1
0.03.31.70.0    1
0.03.51.40.2    1
4.33.01.10.1    1
4.42.91.40.2    1
4.43.01.30.2    1
4.43.21.30.2    1
4.52.31.30.3    1
4.63.11.50.2    1
4.63.21.40.2    1
4.63.41.40.3    1
4.63.61.00.2    1
4.73.20.00.2    1
4.73.21.30.2    1
4.83.01.40.1    1
4.83.01.40.3    1
4.83.11.60.2    1
4.83.41.60.2    1
4.83.41.90.2    1
4.92.43.31.0    1
4.92.54.51.7    1
4.93.01.40.0    1
4.93.10.00.1    1
4.93.11.50.1    2
5.02.03.51.0    1
5.02.33.31.0    1
5.03.01.60.2    1
5.03.21.20.2    1
5.03.31.40.2    1
               ..
6.62.94.61.3    1
6.63.04.41.4    1
6.72.55.81.8    1
6.73.05.01.7    1
6.73.05.22.3    1
6.73.14.41.4    1
6.73.14.71.5    1
6.73.15.62.4    1
6.73.35.72.1    1
6.73.35.72.5    1
6.82.84.81.4    1
6.83.05.52.1    1
6.83.25.92.3    1
6.93.14.91.5    1
6.93.15.12.3    1
6.93.15.42.1    1
6.93.25.72.3    1
7.00.04.71.4    1
7.13.05.92.1    1
7.23.05.81.6    1
7.23.26.01.8    1
7.23.66.12.5    1
7.32.96.31.8    1
7.42.86.

In [ ]:
###### 将 iris_data 的花瓣长度（第3列）以形成分类变量的形式显示。定义：Less than 3 --> ‘small’；3-5 --> ‘medium’；’>=5 --> ‘large’。

In [35]:
bins = [-1,3,5,99]
petal_labels = ['small','medium','large']

rawdata_zero['petal_length_category'] = pd.cut(rawdata_zero['petal length (cm)'],bins = bins,labels=petal_labels)
rawdata_zero[['petal length (cm)','petal_length_category']].head()

petal length (cm) petal_length_category
0                1.4                 small
1                1.4                 small
2                1.3                 small
3                1.5                 small
4                1.4                 small

In [ ]:
###### 在 iris_data 中创建一个新列，其中 volume 是 (pi x petallength x sepallength ^ 2）/ 3。

In [36]:
rawdata['petal_sepal_math'] = np.pi*rawdata['petal length (cm)']*pow(rawdata['sepal length (cm)'],2)/3
rawdata['petal_sepal_math'].head()

0    38.132652
1    35.200498
2    30.072372
3    33.238050
4    36.651914
Name: petal_sepal_math, dtype: float64

In [ ]:
###### 随机抽鸢尾属植物的种类，使得Iris-setosa的数量是Iris-versicolor和Iris-virginica数量的两倍。

In [37]:
rawdata['classes_weight'] = pd.Series(data.target).apply(lambda x: 2 if x==0 else 1)
rawdata['classes_weight'].head()

0    2
1    2
2    2
3    2
4    2
Name: classes_weight, dtype: int64

In [39]:
rawdata.sample(frac = 0.05, weights=rawdata['classes_weight'],random_state=1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
41                4.5               2.3                1.3               0.3   
94                5.6               2.7                4.2               1.3   
0                 5.1               3.5                1.4               0.2   
30                4.8               3.1                1.6               0.2   
14                5.8               4.0                1.2               0.2   
9                 4.9               3.1                1.5               0.1   
18                5.7               3.8                1.7               0.3   
34                4.9               3.1                1.5               0.2   

    class  petal_sepal_math  classes_weight  
41      0         27.567476               2  
94      1        137.928484               1  
0       0         38.132652               2  
30      0         38.603891               2  
14      0         42.273271               2  
9       0         37.714820               2  
18      0         57.839862               2  
34      0         37.714820               2

In [ ]:
###### 根据 sepallength 列对数据集进行排序。

In [41]:
rawdata.sort_values(by='sepal length (cm)').head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
13                4.3               3.0                1.1               0.1   
42                4.4               3.2                1.3               0.2   
38                4.4               3.0                1.3               0.2   
8                 4.4               2.9                1.4               0.2   
41                4.5               2.3                1.3               0.3   

    class  petal_sepal_math  classes_weight  
13      0         21.298951               2  
42      0         26.355868               2  
38      0         26.355868               2  
8       0         28.383242               2  
41      0         27.567476               2

In [ ]:
###### 在鸢尾属植物数据集中找到最常见的花瓣长度值（第3列）。

In [42]:
print('most frequent petal length is {}(cm)'.format(rawdata.groupby(by='petal length (cm)')['class'].count().sort_values(ascending = False).index[0]))

most frequent petal length is 1.5(cm)


In [ ]:
###### 在鸢尾花数据集的 petalwidth（第4列）中查找第一次出现的值大于1.0的位置。

In [43]:
print('row number where petalwidth first > 1.0 is row_{}'.format(rawdata[rawdata['petal width (cm)']>1].index[0]))

row number where petalwidth first > 1.0 is row_50
